### ISSUE TITLE
setting committer details may fail due to GH settings 

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/che-starter#125]
We have observed the below stacktrace when a github user's email was set `not to be displayed`

```
7:28 PM
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:531)
    at io.fabric8.che.starter.client.WorkspacePreferencesClient.setCommiterInfo(WorkspacePreferencesClient.java:43)
    at io.fabric8.che.starter.controller.WorkspaceController.createWorkspace(WorkspaceController.java:156)
    at io.fabric8.che.starter.controller.WorkspaceController.create(WorkspaceController.java:113)
```

**Comment by ibuziuk** [comment]
@gorkem hmm... wondering if there is a way to figure out in advance what is allowed to obtain ?

**Comment by ibuziuk** [comment]
PR is sent - https://github.com/redhat-developer/che-starter/pull/127

**Comment by ibuziuk** [comment]
should be fixed now
